### ISSUE TITLE
请问滑动事件如何传递当前slide的index

### ISSUE THREAD

**Issue by ruichenx** [zwhGithub/vue-swiper#10]
我想滑动时同时带动上面Tab的切换，所以需要传递当前slide的index

**Comment by zwhGithub** [comment]
transtionend 事件  每次轮播出发 参数表示轮播到第几个图片 在Swiper上添加
// @transtionend="getNum"    getNum(data) {console.log(data);}

**Comment by bundery** [comment]
@zwhGithub 我之前写成这样了：@transtionend="getNum()"，所以之前获取到的 data 一直是 undefined.....

**Comment by bundery** [comment]
@zwhGithub 大神，还有一个问题，就是页面打开快时，滑动slide会滑不动，并且控制台报错
![image](https://user-images.githubusercontent.com/24670630/40766231-5f1bc09e-64e1-11e8-8e66-bdec4e3d009d.png)

**Comment by zwhGithub** [comment]
zwh452216418 wechat
