### ISSUE TITLE
安装的包在ssr情况下会出问题

### ISSUE THREAD

**Issue by lennontu** [zwhGithub/vue-swiper#14]
npm发布的包能不能是这个样子, 打包过后的包, 无法在ssr中使用呢

![image](https://user-images.githubusercontent.com/26213241/42992203-74f495d2-8c3a-11e8-8eb7-41d1ca6511d2.png)

**Comment by zwhGithub** [comment]
感觉不应该打包，我也不知道什么原因

**Comment by tlnuaa** [comment]
打出来的包里面包含了 style 是通过 document 加的, 而ssr 没有document变量, 所以会有问题

**Comment by tlnuaa** [comment]
如果css单独打包应该不会有问题, 或者不打包也可以(已经试过了)

**Comment by zwhGithub** [comment]
等晚一点 发布npm包 不打包了，感觉现在很多node_modules都没打包，这样方便看到源码

**Comment by lennontu** [comment]
3q

**Comment by lennontu** [comment]
能先发布个npm包解决这个问题吗?

**Comment by zwhGithub** [comment]
等一下  我准备发包

**Comment by zwhGithub** [comment]
好了

**Comment by lennontu** [comment]
需要webpack 支持
