### ISSUE TITLE
请问项目源码在哪学习下

### ISSUE THREAD

**Issue by chenxuan0000** [zwhGithub/vue-swiper#2]

**Comment by zwhGithub** [comment]
项目源码 就在github上 src下面的 几个vue文件里面，可能注释不够多 ，看起来比较杂

**Comment by chenxuan0000** [comment]
有点好奇 你的npm打包的项目不是这个吗 这个只是个demo吗

**Comment by zwhGithub** [comment]
打包了 index.js、 slide.vue 、swiper.vue  源码就在这三个文件

**Comment by zwhGithub** [comment]
兄弟 看你项目有点骚哦 文档和demo贼鸡吧齐全  你那个实现原理跟我一样的

**Comment by chenxuan0000** [comment]
无缝滚动和轮播还是有点点区别的 没找到这方面插件我才写的这个
